import {
  Add,
  ArrowLeft,
  ArrowRight,
  Branch,
  ChevronDown,
  ChevronRight,
  ChevronSort,
  ChevronUp,
  CircleDash,
  Close,
  CloseFilled,
  ColorPalette,
  Cube,
  Document,
  DocumentAdd,
  Edit,
  Folder,
  FolderAdd,
  FolderOpen,
  Growth,
  LogoGithub,
  Map,
  OverflowMenuHorizontal,
  Pen,
  Pin,
  PinFilled,
  Plug,
  Renew,
  Ruler,
  Search,
  TextFont,
  TrashCan,
  UserAvatar,
  View,
} from "@carbon/icons-react"

export const CARBON_ICONS = {
  add: Add,
  folder: Folder,
  "folder-open": FolderOpen,
  document: Document,
  "color-palette": ColorPalette,
  "text-font": TextFont,
  ruler: Ruler,
  pen: Pen,
  growth: Growth,
  map: Map,
  cube: Cube,
  branch: Branch,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-sort": ChevronSort,
  search: Search,
  "folder-add": FolderAdd,
  "document-add": DocumentAdd,
  "overflow-menu-horizontal": OverflowMenuHorizontal,
  "trash-can": TrashCan,
  edit: Edit,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "circle-dash": CircleDash,
  close: Close,
  "close-filled": CloseFilled,
  "logo-github": LogoGithub,
  pin: Pin,
  "pin-filled": PinFilled,
  plug: Plug,
  renew: Renew,
  "user-avatar": UserAvatar,
  view: View,
} as const

export type CarbonIconName = keyof typeof CARBON_ICONS

export function getCarbonIcon(name: CarbonIconName) {
  return CARBON_ICONS[name]
}
