export const BREADCRUMB_ROW_HEIGHT = 36
export const BREADCRUMB_CHIP_HEIGHT = 22
export const BREADCRUMB_CHEVRON_SIZE = 12

export const BRANCH_DROPDOWN_WIDTH = 240
export const BRANCH_DROPDOWN_MAX_LIST_HEIGHT = 320
export const BRANCH_DROPDOWN_ROW_HEIGHT = 32
